# commit to be tagged for new release
commit = "HEAD"

project_name = "CAPI Bootstrap Provider Talos"
github_repo = "talos-systems/cluster-api-bootstrap-provider-talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.4.1"

pre_release = false

preface = """\
"""

[notes]

    [notes.capi]
        title = "CAPI v1alpha4"
        description = """\
CABPT v0.4.x supports CAPI v1alpha4.
"""

    [notes.talosconfig]
        title = "`talosconfig` Generation"
        description = """\
CABPT now generates client-side Talos API credentials (`talosconfig`) in the `<cluster>-talosconfig` Secret.
Generated `talosconfig` will be updated with the endpoints of the control plane `Machine`s.
"""
