# commit to be tagged for new release
commit = "HEAD"

project_name = "CAPI Bootstrap Provider Talos"
github_repo = "talos-systems/cluster-api-bootstrap-provider-talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.4.0"

pre_release = false

preface = """\
"""

[notes]

    [notes.capi]
        title = "CAPI v1alpha4"
        description = """\
CABPT v0.4.x supports CAPI v1alpha4.
"""

    [notes.talos]
        title = "Talos 0.13.0"
        description = """\
CABPT now supports config generation for Talos 0.13.0 (and previous Talos releases).
Talos version to generate configs for should be specified in the `talosVersion:` field.
"""
