# commit to be tagged for new release
commit = "HEAD"

project_name = "CAPI Bootstrap Provider Talos"
github_repo = "talos-systems/cluster-api-bootstrap-provider-talos"
match_deps = "^github.com/(talos-systems/[a-zA-Z0-9-]+)$"

# previous release
previous = "v0.3.0"

pre_release = false

preface = """\
"""

[notes]

    [notes.talos]
        title = "Talos 0.12.3"
        description = """\
CABPT supports config generation for Talos 0.12.3 (and previous Talos releases).
"""

    [notes.capi]
        title = "CAPI v1alpha3"
        description = """\
This release of CABPT is compatible with CAPI v1alpha3 (v0.3.x).
Next release of CABPT will bring compatibility with CAPI v1alpha4 (v0.4.x).
"""

    [notes.defaultversion]
        title = "configType `none`"
        description = """\
This releases fixes generation of `<cluster>-ca` secret for user-provided machine configuration with `configType: none`
(https://github.com/talos-systems/cluster-api-bootstrap-provider-talos/issues/97).
"""
